name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      # run: docker build **/MvcApp/ --file Dockerfile --tag my-image-name:$(date +%s)

      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        pwd
        ls
        docker build MvcApp/ --file Dockerfile --tag my-image-name:$(date +%s)
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
