name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_REPOSITORY: houssemdocker
        IMAGE_NAME: web-app
        IMAGE_TAG: ${{ github.sha }}

      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        pwd
        ls
        docker build ./MvcApp/ --file ./MvcApp/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
        docker login -u ${{ secrets.DOCKER_REPOSITORY }} -p ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
        echo "::set-output name=image::$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG"
