name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_REPOSITORY: houssemdocker
      IMAGE_NAME: web-app
      IMAGE_TAG: $GITHUB_RUN_NUMBER # ${{ github.sha }}
    
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        echo "::set-output hello"
        echo "$IMAGE_NAME"
        echo "$IMAGE_TAG"
        echo "${{ github.GITHUB_RUN_NUMBER }}"

    - name: Build Docker Image
      run:
        docker build ./MvcApp/ --file ./MvcApp/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
    
    - name: Login to Docker Hub
      run:
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login "https://index.docker.io/v1" -u $DOCKER_REPOSITORY --password-stdin
        
    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
        
    - name: Scan Docker Image using Trivy
      run:
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 0 --severity MEDIUM,HIGH,CRITICAL --ignore-unfixed $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
